class Spelunk < Formula
  desc "Code intelligence for AI agents — persistent memory, code graph, search"
  homepage "https://github.com/spelunk-cloud/spelunk"
  license "MIT"
  version "0.7.1"

  # Tap this repo directly:
  #   brew tap spelunk-cloud/spelunk https://github.com/spelunk-cloud/spelunk
  #   brew install spelunk-cloud/spelunk/spelunk
  #
  # This file is generated by .github/scripts/update-homebrew-formula.js,
  # invoked from the update-homebrew-formula job in
  # .github/workflows/release.yml on every stable tag push. Do not hand-edit
  # the version/sha256 values — they will be overwritten on the next release.
  #
  # Note: x86_64-apple-darwin (Intel Mac) is no longer offered as a prebuilt
  # target — Apple deprecated the architecture and it has not shipped on new
  # hardware in years. Intel Mac users should build from source; see
  # docs/getting-started.md.

  on_macos do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "5bee62a2820b1de394b7c14385d097b23ec11fdafe26180c61f8d79b21b903a1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3e3b897d129089cb1615882d23c9ef2c4b0f3af3482cbda24bf714e1641bcd60"
    end
    on_intel do
      url "https://github.com/spelunk-cloud/spelunk/releases/download/v#{version}/spelunk-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "369c1983639f1d5a68783941b297c833bb27a39eec786b2ea111a72313ad7d77"
    end
  end

  def install
    bin.install "spelunk"
    bin.install "spelunk-server"
  end

  test do
    system "#{bin}/spelunk", "--version"
  end

  def caveats
    <<~EOS
      Run `spelunk init` in a project directory to get started.
      To start the local server: `spelunk server start`
    EOS
  end
end
