use anyhow::{Context, Result};
use rusqlite::{Connection, OptionalExtension};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use spelunk_core::embeddings::blob_to_vec;

/// Shared state for all DB operations on the server.
pub struct ServerDb {
    pub conn: Connection,
    pub embedding_dim: usize,
}

#[derive(Debug, Serialize, Deserialize, Clone, ToSchema)]
pub struct Project {
    pub id: i64,
    pub slug: String,
    pub embedding_dim: usize,
    /// Unix timestamp of project creation.
    pub created_at: i64,
}

#[derive(Debug, Serialize, Deserialize, Clone, ToSchema)]
pub struct ServerNote {
    pub id: i64,
    /// Kind: `decision`, `requirement`, `note`, `question`, `handoff`, or `intent`.
    pub kind: String,
    pub title: String,
    pub body: String,
    pub tags: Vec<String>,
    pub linked_files: Vec<String>,
    /// Unix timestamp of creation.
    pub created_at: i64,
    /// `active` or `archived`.
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub superseded_by: Option<i64>,
    /// Cosine distance from query (only present in search results).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub distance: Option<f64>,
}

impl ServerDb {
    pub fn open(path: &std::path::Path, embedding_dim: usize) -> Result<Self> {
        let conn = Connection::open(path)
            .with_context(|| format!("opening server db at {}", path.display()))?;
        // WAL mode for concurrent readers.
        conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;")?;
        let db = Self {
            conn,
            embedding_dim,
        };
        db.migrate()?;
        Ok(db)
    }

    fn migrate(&self) -> Result<()> {
        self.conn
            .execute_batch(include_str!("../migrations/server_001.sql"))
            .context("server migration 001")?;
        // Create the embeddings virtual table with the configured dimension.
        // IF NOT EXISTS means this is a no-op if the table already exists.
        self.conn
            .execute_batch(&format!(
                "CREATE VIRTUAL TABLE IF NOT EXISTS note_embeddings USING vec0(\
                    note_id INTEGER PRIMARY KEY, embedding FLOAT[{dim}]\
                )",
                dim = self.embedding_dim
            ))
            .context("creating note_embeddings virtual table")?;
        self.conn
            .execute_batch(include_str!("../migrations/server_002.sql"))
            .context("server migration 002")?;
        self.conn
            .execute_batch(include_str!("../migrations/server_003.sql"))
            .context("server migration 003")?;
        Ok(())
    }

    /// Return the persistent instance UUID, creating one on first call.
    ///
    /// Uses SQLite's `randomblob(16)` for entropy so no extra deps are needed.
    /// The generated bytes are formatted as a proper UUID v7 string: the high
    /// 48 bits carry the millisecond Unix timestamp of creation, with the
    /// version (7) and RFC-4122 variant bits set over the remaining random
    /// entropy.
    pub fn get_or_create_instance_id(&self) -> Result<String> {
        // Insert a random 16-byte blob on first call; IGNORE if already present.
        self.conn
            .execute(
                "INSERT OR IGNORE INTO server_meta(key, value) \
                 VALUES ('instance_id', lower(hex(randomblob(16))))",
                [],
            )
            .context("seeding instance_id")?;
        let raw: String = self
            .conn
            .query_row(
                "SELECT value FROM server_meta WHERE key = 'instance_id'",
                [],
                |row| row.get(0),
            )
            .context("reading instance_id")?;
        Ok(format_uuid_v7(&raw, unix_ts_millis()))
    }

    // ── Projects ──────────────────────────────────────────────────────────────

    /// Get or auto-create a project by slug. On first write, records the
    /// embedding dimension for subsequent validation.
    pub fn upsert_project(&self, slug: &str, incoming_dim: usize) -> Result<Project> {
        // Check if project exists.
        let existing: Option<Project> = self
            .conn
            .query_row(
                "SELECT id, slug, embedding_dim, created_at FROM projects WHERE slug = ?1",
                rusqlite::params![slug],
                row_to_project,
            )
            .optional()
            .context("querying project")?;

        if let Some(mut p) = existing {
            // Validate dimension if already set.
            if p.embedding_dim != 0 && p.embedding_dim != incoming_dim {
                anyhow::bail!(
                    "embedding dimension mismatch for project '{}': server expects {}, got {}. \
                     All clients on the same project must use the same embedding model.",
                    slug,
                    p.embedding_dim,
                    incoming_dim
                );
            }
            // Set dimension on first note.
            if p.embedding_dim == 0 {
                self.conn.execute(
                    "UPDATE projects SET embedding_dim = ?1 WHERE id = ?2",
                    rusqlite::params![incoming_dim as i64, p.id],
                )?;
                p.embedding_dim = incoming_dim;
            }
            Ok(p)
        } else {
            // Auto-create.
            self.conn.execute(
                "INSERT INTO projects (slug, embedding_dim) VALUES (?1, ?2)",
                rusqlite::params![slug, incoming_dim as i64],
            )?;
            let id = self.conn.last_insert_rowid();
            Ok(Project {
                id,
                slug: slug.to_string(),
                embedding_dim: incoming_dim,
                created_at: now_unix(),
            })
        }
    }

    pub fn get_project(&self, slug: &str) -> Result<Option<Project>> {
        self.conn
            .query_row(
                "SELECT id, slug, embedding_dim, created_at FROM projects WHERE slug = ?1",
                rusqlite::params![slug],
                row_to_project,
            )
            .optional()
            .context("querying project")
    }

    pub fn list_projects(&self) -> Result<Vec<Project>> {
        let mut stmt = self
            .conn
            .prepare("SELECT id, slug, embedding_dim, created_at FROM projects ORDER BY slug")?;
        let projects = stmt
            .query_map([], row_to_project)?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(projects)
    }

    // ── Notes ─────────────────────────────────────────────────────────────────

    #[allow(clippy::too_many_arguments)]
    pub fn add_note(
        &self,
        project_id: i64,
        kind: &str,
        title: &str,
        body: &str,
        tags: &[String],
        linked_files: &[String],
        embedding: Option<&[f32]>,
    ) -> Result<i64> {
        let tags_csv = if tags.is_empty() {
            None
        } else {
            Some(tags.join(","))
        };
        let files_csv = if linked_files.is_empty() {
            None
        } else {
            Some(linked_files.join(","))
        };
        self.conn.execute(
            "INSERT INTO notes (project_id, kind, title, body, tags, linked_files)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            rusqlite::params![project_id, kind, title, body, tags_csv, files_csv],
        )?;
        let note_id = self.conn.last_insert_rowid();

        if let Some(vec) = embedding {
            let blob = spelunk_core::embeddings::vec_to_blob(vec);
            self.conn.execute(
                "INSERT INTO note_embeddings (note_id, embedding) VALUES (?1, ?2)",
                rusqlite::params![note_id, blob],
            )?;
        }
        Ok(note_id)
    }

    pub fn get_note(&self, project_id: i64, note_id: i64) -> Result<Option<ServerNote>> {
        self.conn
            .query_row(
                "SELECT id, kind, title, body, tags, linked_files, created_at, status, superseded_by
                 FROM notes WHERE id = ?1 AND project_id = ?2",
                rusqlite::params![note_id, project_id],
                row_to_note,
            )
            .optional()
            .context("querying note")
    }

    pub fn list_notes(
        &self,
        project_id: i64,
        kind_filter: Option<&str>,
        limit: usize,
        include_archived: bool,
    ) -> Result<Vec<ServerNote>> {
        let limit = limit.min(500);
        let status_clause = if include_archived {
            ""
        } else {
            "AND status = 'active'"
        };
        let (sql, params): (String, Vec<Box<dyn rusqlite::types::ToSql>>) = if let Some(kind) =
            kind_filter
        {
            (
                    format!(
                        "SELECT id, kind, title, body, tags, linked_files, created_at, status, superseded_by
                         FROM notes WHERE project_id = ?1 AND kind = ?2 {status_clause}
                         ORDER BY created_at DESC LIMIT {limit}"
                    ),
                    vec![Box::new(project_id), Box::new(kind.to_string())],
                )
        } else {
            (
                    format!(
                        "SELECT id, kind, title, body, tags, linked_files, created_at, status, superseded_by
                         FROM notes WHERE project_id = ?1 {status_clause}
                         ORDER BY created_at DESC LIMIT {limit}"
                    ),
                    vec![Box::new(project_id)],
                )
        };
        let mut stmt = self.conn.prepare(&sql)?;
        let refs: Vec<&dyn rusqlite::types::ToSql> = params.iter().map(|p| p.as_ref()).collect();
        let notes = stmt
            .query_map(refs.as_slice(), row_to_note)?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(notes)
    }

    pub fn search_notes(
        &self,
        project_id: i64,
        query_vec: &[f32],
        limit: usize,
    ) -> Result<Vec<ServerNote>> {
        let limit = limit.min(100);
        let blob = spelunk_core::embeddings::vec_to_blob(query_vec);
        let sql = format!(
            "WITH knn AS (
                 SELECT note_id, distance
                 FROM   note_embeddings
                 WHERE  embedding MATCH ?1 AND k = {limit}
             )
             SELECT n.id, n.kind, n.title, n.body, n.tags, n.linked_files,
                    n.created_at, n.status, n.superseded_by, CAST(k.distance AS REAL)
             FROM   knn k
             JOIN   notes n ON n.id = k.note_id
             WHERE  n.project_id = ?2 AND n.status = 'active'
             ORDER  BY k.distance"
        );
        let mut stmt = self.conn.prepare(&sql)?;
        let notes = stmt
            .query_map(
                rusqlite::params![blob, project_id],
                row_to_note_with_distance,
            )?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(notes)
    }

    /// Search for existing active notes that are semantically close to the given embedding.
    /// Returns notes with cosine distance ≤ `max_distance` (i.e. similarity ≥ `1 - max_distance`),
    /// excluding `exclude_id` (the note just written).
    pub fn search_notes_for_conflicts(
        &self,
        project_id: i64,
        query_vec: &[f32],
        max_distance: f32,
        exclude_id: i64,
        limit: usize,
    ) -> Result<Vec<ServerNote>> {
        let limit = limit.min(50);
        let blob = spelunk_core::embeddings::vec_to_blob(query_vec);
        // We search with a generous k (limit + 1 for the excluded entry) and filter in Rust.
        let search_limit = limit + 1;
        let sql = format!(
            "WITH knn AS (
                 SELECT note_id, distance
                 FROM   note_embeddings
                 WHERE  embedding MATCH ?1 AND k = {search_limit}
             )
             SELECT n.id, n.kind, n.title, n.body, n.tags, n.linked_files,
                    n.created_at, n.status, n.superseded_by, CAST(k.distance AS REAL)
             FROM   knn k
             JOIN   notes n ON n.id = k.note_id
             WHERE  n.project_id = ?2
               AND  n.status = 'active'
               AND  n.id != ?3
               AND  k.distance <= ?4
             ORDER  BY k.distance
             LIMIT  {limit}"
        );
        let mut stmt = self.conn.prepare(&sql)?;
        let notes = stmt
            .query_map(
                rusqlite::params![blob, project_id, exclude_id, max_distance as f64],
                row_to_note_with_distance,
            )?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(notes)
    }

    /// Insert a directed edge between two server notes.
    /// `kind` must be one of: supersedes, relates_to, contradicts.
    pub fn add_edge(&self, from_id: i64, to_id: i64, kind: &str) -> Result<()> {
        const VALID_KINDS: &[&str] = &["supersedes", "relates_to", "contradicts"];
        if !VALID_KINDS.contains(&kind) {
            anyhow::bail!(
                "invalid edge kind '{kind}'; must be one of: supersedes, relates_to, contradicts"
            );
        }
        self.conn.execute(
            "INSERT OR IGNORE INTO note_edges (from_id, to_id, kind) VALUES (?1, ?2, ?3)",
            rusqlite::params![from_id, to_id, kind],
        )?;
        Ok(())
    }

    /// Return all git SHAs stored in tags for a project.
    ///
    /// Tags are stored as comma-separated strings; each SHA is stored as `git:<sha>`.
    /// Used by the client's `harvested_shas()` to avoid re-harvesting commits.
    pub fn harvested_shas(&self, project_id: i64) -> Result<Vec<String>> {
        let mut stmt = self.conn.prepare_cached(
            "SELECT tags FROM notes WHERE project_id = ?1 AND tags LIKE '%git:%'",
        )?;
        let rows = stmt.query_map(rusqlite::params![project_id], |r| {
            r.get::<_, Option<String>>(0)
        })?;
        let mut shas = Vec::new();
        for row in rows {
            if let Some(tags) = row? {
                for tag in tags.split(',').map(str::trim) {
                    if let Some(sha) = tag.strip_prefix("git:") {
                        shas.push(sha.to_string());
                    }
                }
            }
        }
        Ok(shas)
    }

    pub fn archive_note(&self, project_id: i64, note_id: i64) -> Result<bool> {
        let changed = self.conn.execute(
            "UPDATE notes SET status = 'archived' WHERE id = ?1 AND project_id = ?2 AND status = 'active'",
            rusqlite::params![note_id, project_id],
        )?;
        Ok(changed > 0)
    }

    pub fn supersede_note(&self, project_id: i64, old_id: i64, new_id: i64) -> Result<bool> {
        let changed = self.conn.execute(
            "UPDATE notes SET status = 'archived', superseded_by = ?3
             WHERE id = ?1 AND project_id = ?2 AND status = 'active'",
            rusqlite::params![old_id, project_id, new_id],
        )?;
        Ok(changed > 0)
    }

    /// Return notes created after `since_secs` (exclusive), ordered ASC by `created_at`.
    /// Archived entries are excluded. `limit` is capped at 500.
    pub fn notes_since(
        &self,
        project_id: i64,
        since_secs: i64,
        limit: i64,
    ) -> Result<Vec<ServerNote>> {
        let limit = limit.clamp(1, 500);
        let mut stmt = self.conn.prepare_cached(
            "SELECT id, kind, title, body, tags, linked_files, created_at, status, superseded_by
             FROM notes
             WHERE project_id = ?1 AND created_at > ?2 AND status != 'archived'
             ORDER BY created_at ASC
             LIMIT ?3",
        )?;
        let notes = stmt
            .query_map(
                rusqlite::params![project_id, since_secs, limit],
                row_to_note,
            )?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        Ok(notes)
    }

    pub fn delete_note(&self, project_id: i64, note_id: i64) -> Result<bool> {
        self.conn.execute(
            "DELETE FROM note_embeddings WHERE note_id = ?1",
            rusqlite::params![note_id],
        )?;
        let changed = self.conn.execute(
            "DELETE FROM notes WHERE id = ?1 AND project_id = ?2",
            rusqlite::params![note_id, project_id],
        )?;
        Ok(changed > 0)
    }

    pub fn stats(&self, project_id: i64) -> Result<ProjectStats> {
        let total: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM notes WHERE project_id = ?1",
            rusqlite::params![project_id],
            |r| r.get(0),
        )?;
        let count: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM notes WHERE project_id = ?1 AND status = 'active'",
            rusqlite::params![project_id],
            |r| r.get(0),
        )?;
        Ok(ProjectStats {
            count,
            total,
            embedding_dim: self.embedding_dim,
        })
    }
}

#[derive(Serialize, ToSchema)]
pub struct ProjectStats {
    /// Number of active memory entries.
    pub count: i64,
    /// Total entries including archived.
    pub total: i64,
    pub embedding_dim: usize,
}

// ── Row mappers ──────────────────────────────────────────────────────────────

fn row_to_project(row: &rusqlite::Row<'_>) -> rusqlite::Result<Project> {
    Ok(Project {
        id: row.get(0)?,
        slug: row.get(1)?,
        embedding_dim: row.get::<_, i64>(2)? as usize,
        created_at: row.get(3)?,
    })
}

fn split_csv(s: Option<&str>) -> Vec<String> {
    s.unwrap_or("")
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(String::from)
        .collect()
}

fn row_to_note(row: &rusqlite::Row<'_>) -> rusqlite::Result<ServerNote> {
    Ok(ServerNote {
        id: row.get(0)?,
        kind: row.get(1)?,
        title: row.get(2)?,
        body: row.get(3)?,
        tags: split_csv(row.get::<_, Option<String>>(4)?.as_deref()),
        linked_files: split_csv(row.get::<_, Option<String>>(5)?.as_deref()),
        created_at: row.get(6)?,
        status: row.get(7)?,
        superseded_by: row.get(8)?,
        distance: None,
    })
}

fn row_to_note_with_distance(row: &rusqlite::Row<'_>) -> rusqlite::Result<ServerNote> {
    Ok(ServerNote {
        id: row.get(0)?,
        kind: row.get(1)?,
        title: row.get(2)?,
        body: row.get(3)?,
        tags: split_csv(row.get::<_, Option<String>>(4)?.as_deref()),
        linked_files: split_csv(row.get::<_, Option<String>>(5)?.as_deref()),
        created_at: row.get(6)?,
        status: row.get(7)?,
        superseded_by: row.get(8)?,
        distance: Some(row.get(9)?),
    })
}

fn now_unix() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

fn unix_ts_millis() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

// Need blob_to_vec for search — it's in embeddings module so the import works.
// But we also need vec_to_blob for the vec0 match query. Both are in spelunk_core::embeddings.
impl ServerDb {
    /// Convenience: decode a raw embedding blob to f32 vec for use with search_notes.
    pub fn decode_embedding(blob: &[u8]) -> Vec<f32> {
        blob_to_vec(blob)
    }
}

/// Build a UUID v7 string from a 32-char lowercase hex string of random
/// entropy and a millisecond Unix timestamp.
///
/// Per the RFC 4122 (rev) UUIDv7 layout, the high 48 bits (first 12 hex
/// nibbles) carry `unix_ts_ms` big-endian, the version nibble (byte 6, upper
/// nibble) is set to `7`, and the variant bits (byte 8, upper two bits) are set
/// to `10`. The remaining nibbles retain the supplied random entropy. Dashes
/// are inserted in the canonical 8-4-4-4-12 positions.
fn format_uuid_v7(hex: &str, unix_ts_ms: u64) -> String {
    // hex must be exactly 32 lowercase hex chars (e.g. from randomblob(16)).
    // Work on bytes for efficiency; all chars are ASCII.
    let b = hex.as_bytes();

    // Render the low 48 bits of the timestamp as 12 big-endian hex nibbles.
    let ts = unix_ts_ms & 0x0000_FFFF_FFFF_FFFF;
    let mut ts_nibbles = [0u8; 12];
    for (i, slot) in ts_nibbles.iter_mut().enumerate() {
        let shift = (11 - i) * 4;
        let nibble = ((ts >> shift) & 0xf) as u8;
        *slot = match nibble {
            0..=9 => b'0' + nibble,
            _ => b'a' + (nibble - 10),
        };
    }

    // Version = 7 at nibble index 12 (byte 6, upper nibble).
    let version_nibble = b'7';
    // Variant = 10xx at nibble index 16 (byte 8, upper nibble): map random
    // 0-f into the 8-b range so the top two bits are `10`.
    let variant_nibble = match b[16] {
        c @ b'0'..=b'3' => c - b'0' + b'8', // 0-3 → 8-b
        c @ b'4'..=b'7' => c - b'4' + b'8',
        c @ b'8'..=b'b' => c, // already 8-b, valid
        _ => b'a',
    };

    let mut out = Vec::with_capacity(36);
    out.extend_from_slice(&ts_nibbles[0..8]);
    out.push(b'-');
    out.extend_from_slice(&ts_nibbles[8..12]);
    out.push(b'-');
    out.push(version_nibble);
    out.extend_from_slice(&b[13..16]);
    out.push(b'-');
    out.push(variant_nibble);
    out.extend_from_slice(&b[17..20]);
    out.push(b'-');
    out.extend_from_slice(&b[20..32]);
    String::from_utf8(out).unwrap_or_else(|_| hex.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_uuid_v7_has_version_and_variant() {
        // 32 hex chars of arbitrary entropy.
        let raw = "0123456789abcdef0123456789abcdef";
        let id = format_uuid_v7(raw, 0x0190_1234_5678);

        // Canonical 8-4-4-4-12 hyphenated form.
        assert_eq!(id.len(), 36);
        let parts: Vec<&str> = id.split('-').collect();
        assert_eq!(
            parts.iter().map(|p| p.len()).collect::<Vec<_>>(),
            vec![8, 4, 4, 4, 12]
        );

        let nibbles: Vec<u8> = id.bytes().filter(|&c| c != b'-').collect();
        // Version nibble (13th hex char) must be 7.
        assert_eq!(nibbles[12], b'7', "version nibble must be 7");
        // Variant nibble (17th hex char) must have top two bits = 10 (8..=b).
        assert!(
            matches!(nibbles[16], b'8'..=b'b'),
            "variant bits must be 10xx"
        );
    }

    #[test]
    fn format_uuid_v7_encodes_timestamp_high_bits() {
        let raw = "ffffffffffffffffffffffffffffffff";
        let ts: u64 = 0x0000_017F_2C3D_4E5F;
        let id = format_uuid_v7(raw, ts);
        // First 12 hex nibbles (positions 0-7 and 9-12, skipping the dash) are
        // the big-endian low 48 bits of the timestamp.
        let hex_ts: String = id.chars().take(13).filter(|&c| c != '-').collect();
        assert_eq!(hex_ts, format!("{:012x}", ts & 0x0000_FFFF_FFFF_FFFF));
    }
}
