-- A stored vector no longer reflects the chunk's current embedding_text() and
-- must be re-embedded in place. Two writers set it: the one-time summary-scheme
-- transition (below, in the migration runner) marks every already-embedded
-- chunk when an existing index first meets the structural-summary composition,
-- and tier-3 MMR selection marks a title-less chunk after rewriting its summary
-- slot. It is cleared in the same transaction as the replacement vector write,
-- so a kill mid-batch rolls back both and the batch re-queues cleanly.
-- DEFAULT 0 keeps every fresh chunk and every pre-migration row current until
-- something explicitly marks it stale; the column is additive, so an older
-- binary simply ignores it.
ALTER TABLE chunks ADD COLUMN embed_pending INTEGER NOT NULL DEFAULT 0;
